### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by jbilbro** [jctanner/ansible-vmware-pyvmomi#1]
Can you get me started on usage of this?  I have put in my vcenter hostname, username, and password in the ini file, but when I try to run vmware_inventory.py --list I get the error: 

socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by jctanner** [comment]
This repo is deprecrated, please use the script from the main repo: https://github.com/ansible/ansible/blob/devel/contrib/inventory/vmware_inventory.py
